FROM n8nio/n8n

# Optional: Set default timezone
ENV GENERIC_TIMEZONE=Europe/Madrid

# Optional: Enable basic auth for security
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=strong-password
ENV N8N_EDITOR_BASE_URL=https://localhost:5678/workflow/leHyOX4gWG2TjeVl.onrender.com

# Expose port (Render auto-detects this)
EXPOSE 5678
